### ISSUE TITLE
Test settings time limit validation bug

### ISSUE THREAD

**Issue by garretttaco** [bradwestfall/questionable-issues#1]
Great Job on the app, it is fantastic!

### Where 
`tests/:testId/settings`

### What
The time limit component appears to be partially broken.
I noticed that it autosaves when I change the number (default is 20), so when I refresh afterward, I can tell that my changes were saved successfully. 
However, when I toggle the setting, time limit, to off, the section gives me an error saying that a time limit is required. If I refresh, I can see that the setting gets turned back on, implying that the setting was not saved. If I toggle it off again, and then back on, I can see that the default time is gone and the text box is empty. The error continues to be displayed, implying to me that the textbox, although hidden, is still validating the input and the state is just being cleared. 

Here are a couple screenshots to solidify my findings.
<img width="761" alt="screen shot 2018-02-16 at 2 08 20 pm" src="https://user-images.githubusercontent.com/10181154/36329364-021d4972-1323-11e8-9684-70ea5b645b8c.png">
<img width="730" alt="screen shot 2018-02-16 at 2 08 26 pm" src="https://user-images.githubusercontent.com/10181154/36329373-04985d0e-1323-11e8-85aa-15d73205d940.png">
<img width="743" alt="screen shot 2018-02-16 at 2 08 31 pm" src="https://user-images.githubusercontent.com/10181154/36329375-0718f3ae-1323-11e8-86e1-a345e64c26af.png">

Hope this helps!

**Comment by bradwestfall** [comment]
Thanks @garretttaco 

And thanks for finding this buggy behavior. I made the UI more clear for this now. Will go out with next deployment
