### ISSUE TITLE
Hitting `enter` submits form & refreshes page

### ISSUE THREAD

**Issue by kylecesmat** [bradwestfall/questionable-issues#5]
https://app.questionable.io/tests/87/assign?

When editing the shared link, I type into the input and press `enter` - and the form submits & refreshes the page.

![feb-16-2018 15-47-57](https://user-images.githubusercontent.com/1633837/36332784-cf20c48c-1330-11e8-9a0d-804faf3fb142.gif)

**Comment by bradwestfall** [comment]
Thanks for finding that. I haven't looked at the code yet but if I remember, it's just an `<input>` without a `<form>`, so I'm curious why it would respond to enter key

**Comment by bradwestfall** [comment]
Fixed, it was a form wrapping the field. Now I handle it like a boss. Will go out with next deployment
