### ISSUE TITLE
Let users click on whole answer to select it

### ISSUE THREAD

**Issue by troym9731** [bradwestfall/questionable-issues#7]
Picture just for clarity: 
<img width="1067" alt="screen shot 2018-03-11 at 12 00 35 pm" src="https://user-images.githubusercontent.com/12416548/37257258-2f788b30-2524-11e8-9bc1-9788e738e4df.png">

**Comment by bradwestfall** [comment]
Thanks @troym9731, yea this is on our short list to get done soon. Glad you think so too :)

**Comment by bradwestfall** [comment]
Fixed, will go out with next deployment
