### ISSUE TITLE
Clear out password fields after updating (maybe?)

### ISSUE THREAD

**Issue by troym9731** [bradwestfall/questionable-issues#8]
Because of the helpful notification, I know that the update went through successfully. However, perhaps I'm just used to most forms clearing out the fields after a successful submission, that it threw me off a bit to see the fields still populated. Not really an issue if you want to keep the current behavior, just thought I'd bring it up.

![questionableio](https://user-images.githubusercontent.com/12416548/37257291-cde481a2-2524-11e8-9ec2-44f064d099c4.gif)

**Comment by bradwestfall** [comment]
@troym9731 Yep, I agree, I think it used to do that and for some reason though some change it stopped. I'll get it fixed. Thank you

**Comment by bradwestfall** [comment]
Fixed, will go out with next deploy
